name: build_test

on: 
  push:
    paths: 
      - build_test/**
      - .github/workflows/build_test.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build_test
          ./make_android_lua54.sh
          ./make_android_lua53.sh
          sudo apt install gcc-multilib
          ./make_android_luajit_arm64.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_luajit/**/*
          name: plugin_luajit
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build_test
          ./make_linux_lua54.sh
          ./make_linux64_lua53.sh
          ./make_linux64_luajit.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_luajit/**/*
          name: plugin_luajit  
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build_test
          ./make_ios_lua54.sh
          ./make_ios_lua53.sh
          ./make_ios_luajit.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_luajit/**/*
          name: plugin_luajit
  osx:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build_test
          ./make_osx_lua54.sh
          ./make_osx_lua53.sh
          ./make_osx_luajit.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_luajit/**/*
          name: plugin_luajit  
  windows:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd build_test
          .\make_win_lua54.bat
          .\make_win32_lua53.bat
          .\make_win64_lua53.bat
          .\make_win32_luajit.bat
          .\make_win64_luajit.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build_test/plugin_luajit/**/*
          name: plugin_luajit
    

   
